package fr.insarennes.learningbot.controller;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import kc.micro.Thorn;
import robocode.ScannedRobotEvent;
import fr.insarennes.learningbot.model.DecisionTree;
import fr.insarennes.learningbot.model.LearnedData;

public class LearningBot extends Thorn {
//ATTRIBUTES
	/** The decision tree generated by BonzaiBoost (c) **/
	private static DecisionTree tree;
	/** All the data acquired during battle (static to keep it over time) **/
	private static List<LearnedData> knowledge = new ArrayList<LearnedData>();
	/** The file which contains the decision tree **/
	private static final String PATH_TREE = "/tmp/tree.xml";

//CONSTRUCTOR
	/**
	 * Class constructor
	 */
	public LearningBot() {
		super();
		
		//Load tree if needed
		if(tree == null) {
			DecisionTreeParser dtp = new DecisionTreeParser();
			tree = dtp.parse(new File(PATH_TREE));
		}
	}

//ACCESSORS
	
//MODIFIERS
	
//OTHER METHODS
	/**
	 * This method is launched when a battle starts
	 */
	public void run() {
		if(tree == null) {
			super.run();
		}
		else {
			//TODO
		}
	}
	
	/**
	 * This method is called when a robot is detected
	 */
	public void onScannedRobot(ScannedRobotEvent e) {
		knowledge.add(new LearnedData(e));
		if(tree == null) {
			super.onScannedRobot(e);
		}
		else {
			//TODO
			//Decision for shoot
			//Decision for movement
		}
	}
}
