package fr.insarennes.learningbot.controller;

import java.util.ArrayList;
import java.util.List;

import kc.micro.Thorn;
import fr.insarennes.learningbot.model.DecisionTree;
import fr.insarennes.learningbot.model.LearnedData;

public class LearningBot extends Thorn {
//ATTRIBUTES
	/** The decision tree generated by BonzaiBoost (c) **/
	private DecisionTree tree;
	/** All the data acquired during battle (static to keep it over time) **/
	private static List<LearnedData> knowledge = new ArrayList<LearnedData>();

//CONSTRUCTOR
	/**
	 * Class constructor
	 */
	public LearningBot() {
		super();
	}

//ACCESSORS
	
//MODIFIERS
	
//OTHER METHODS
	/**
	 * This method is launched when a battle starts
	 */
	public void run() {
		if(tree == null) {
			super.run();
		}
		else {
			//TODO
		}
	}
}
